from GoogleTS import GoogleTranslate    
import re

def main():    
    google_ts = GoogleTranslate()    
         
    content = """The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.
 
The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

The latest trial allows people to check in without producing a paper ticket, which was previously1 necessary even for passengers who have bought tickets online.
Starting November 22, Hainan locals who succeed in purchasing an island-looping high-speed ticket will have access to an information sheet, which includes a QR code.
They can then check in by swiping the QR code, whether via an electronic or printed version.
Swiping ID cards, or a QR code generated by an official app on mobile phones, are also available for station check-in.

hello,what is your name? and you, I'm fine
hello,what is your name? and you, I'm fine
hello,what is your name? and you, I'm fine,hello,what are you doing?I love you"""
 
    #content = 'Die neueste Testversion ermöglicht das Einchecken ohne Vorlage eines Papiertickets. Dies war bisher auch für Passagiere erforderlich, die Tickets online gekauft haben.'
    length = len(content)
    print('len=' + str(length))
    print(google_ts.translate_cn(content))

if __name__ == "__main__":    
    main()
    